### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rstyle'

### ISSUE THREAD

**Issue by bstamps** [smdabdoub/phylotoast#64]
When attempting to run the PCoA_bubble.py script, I run into the below error: 

`Traceback (most recent call last):
  File "/usr/local/bin/PCoA_bubble.py", line 254, in <module>
    main()
  File "/usr/local/bin/PCoA_bubble.py", line 251, in main
    category_colors, xr, yr, args.output_dir)
  File "/usr/local/bin/PCoA_bubble.py", line 109, in plot_PCoA
    graph_util.rstyle(ax)
AttributeError: 'module' object has no attribute 'rstyle'`

From my googling of the issue I'm assuming this has to do with matplotlib, but beyond that I'm helpless. As an aside- there are pretty major differences in the input of this script in the documentation online and the script-as-installed... but that could be the difference between the pip installed version and the github installed version correct?

## My Environment
* Version used: pip installed (So I assume up-to-date)
* Operating System and version: Ubuntu 16.04.1 LTS

**Comment by bstamps** [comment]
This appears to be an issue with the PyPi version of Phylotoast- from what I can tell (With my lack of knowledge of Python) the util.py script has no definition for the 'rstyle' attribute. Removing the PyPi version and installing the Github repo version of Phylotoast appears to fix the issue.

**Comment by smdabdoub** [comment]
Thank you for the report! Your followup message is correct. That method was renamed at some point and the PCoA_bubble script was unfortunately not updated before the 1.3 release.

The 1.3 release is now sufficiently old that I would definitely recommend installing from the git repo as you did. In addition, as you noticed, the documentation has kept current with the code in the repository, even though the version number on the documentation still reads 1.3.0.

Technically the official documentation for the last release is under the 'stable' docs: [phylotoast.readthedocs.io/en/stable/](http://phylotoast.readthedocs.io/en/stable/)

The 'latest' docs which is the default when going to [docs.phylotoast.org](http://docs.phylotoast.org) reflects the latest built documentation from the GitHub repository.

Since you pointed this out (and because we're close to an official 1.4 release), I've updated the version number in the setup.py and in the docs to 1.4.0rc1 to make sure people are current.
